CREATE DATABASE QLHoSoBenhAn
USE QLHoSoBenhAn
DROP DATABASE  QLHoSoBenhAn


CREATE TABLE HoSoBenhAn(
	IDHoSo CHAR(9) NOT NULL,
	HoVaTenBN NVARCHAR(50) NOT NULL,
	DCHI NVARCHAR(50) NOT NULL,
	NSINH DATETIME NOT NULL,
	PHONE INT NOT NULL,
	NgayLapHoSo DATETIME,
	NgayHetHanHoSo DATETIME 
)


CREATE TABLE PhieuDangKyKhamBenh
(
	IDDK CHAR(9) NOT NULL,
	IDHoSo CHAR(9)
)


CREATE TABLE LePhi
(
	IDHoaDon CHAR(9) NOT NULL,
	NgDONG DATETIME NOT NULL,
	SoTienLePhi INT NOT NULL,
	IDHoSo CHAR(9)
)


CREATE TABLE PhieuNhapXuatVien
(
	IDPHIEU CHAR(9) NOT NULL,
	NGAYNHAP DATETIME NOT NULL,
	NGAYXUAT DATETIME NOT NULL,
	IDHoSo CHAR(9)
)


CREATE TABLE VienPhi
(
	IDVP CHAR(9) NOT NULL,
	NDONGVP DATETIME NOT NULL,
	TTOANVP INT NOT NULL,
	IDHoSo CHAR(9)
)


CREATE TABLE BacSi
(
	IDBacSi CHAR(9) NOT NULL,
	HoVaTenBS  NVARCHAR(50) NOT NULL,
	DiaChiBS NVARCHAR(50) NOT NULL,
	PHONEBS INT,
	IDKHoa CHAR(9)
)


CREATE TABLE PhieuKhamBenh
(
	IDPKB CHAR(9) NOT NULL,
	NgayGioKham DATETIME NOT NULL,
	IDHoSo CHAR(9)
)


CREATE TABLE PhieuXetNghiem
(
	IDXN CHAR(9) NOT NULL,
	TenXetNghiem NVARCHAR(50) NOT NULL,
	NgayXetNghiem DATETIME NOT NULL,
	KQUA	NVARCHAR(50) NOT NULL,
	IDHoSo CHAR(9)
)



CREATE TABLE ChiTietPhieuKhamBenh
(
	IDPKB CHAR(9) NOT NULL,
	TrieuChung NVARCHAR(50) NOT NULL,
	IDBENH CHAR(9),
	IDBacSi CHAR(9)
)


CREATE TABLE ToaThuoc
(
	IDToaThuoc CHAR(9) NOT NULL,
	NgayLapToaThuoc DateTime NOT NULL,
	IDPKB CHAR(9),
	IDBENH CHAR(9),
	IDDonThuoc CHAR(9)
)

CREATE TABLE Thuoc 
(
	IDThuoc CHAR (9) NOT NULL,
	TenThuoc nvarchar (50) Not NULL,
	HuongDanSuDung nvarchar (150) Not NULL, 
)


CREATE TABLE KHOA
(
	IDKHoa CHAR(9) NOT NULL,
	TenKhoa NVARCHAR(50) NOT NULL,
)


CREATE TABLE BENH
(
	IDBENH CHAR(9) NOT NULL,
	TenBenh NVARCHAR(50) NOT NULL,
)



CREATE TABLE ChiTietDonThuoc
(
	IDDonThuoc CHAR(9) NOT NULL,
	SoLuongThuoc INT,
	IDThuoc CHAR (9)
)


--Khóa Chính của các bảng: 
ALTER TABLE HoSoBenhAn ADD CONSTRAINT PK_IDHoSo PRIMARY KEY (IDHoSo)
ALTER TABLE PhieuDangKyKhamBenh ADD CONSTRAINT PK_IDDK PRIMARY KEY (IDDK)
ALTER TABLE LePhi ADD CONSTRAINT PK_IDHoaDon PRIMARY KEY (IDHoaDon)
ALTER TABLE PhieuNhapXuatVien ADD CONSTRAINT PK_IDPHIEU PRIMARY KEY (IDPHIEU)
ALTER TABLE VienPhi ADD CONSTRAINT PK_IDVP PRIMARY KEY (IDVP)
ALTER TABLE BacSi ADD CONSTRAINT PK_IDBacSi PRIMARY KEY (IDBacSi)
ALTER TABLE PhieuKhamBenh ADD CONSTRAINT PK_IDPKB PRIMARY KEY (IDPKB)
ALTER TABLE PhieuXetNghiem ADD CONSTRAINT PK_IDXN PRIMARY KEY (IDXN)
ALTER TABLE ChiTietPhieuKhamBenh ADD CONSTRAINT PK_IDPKBENH PRIMARY KEY (IDPKB)
ALTER TABLE ToaThuoc ADD CONSTRAINT PK_IDToaThuoc PRIMARY KEY (IDToaThuoc)
ALTER TABLE Thuoc  ADD CONSTRAINT PK_IDThuoc PRIMARY KEY (IDThuoc)
ALTER TABLE KHOA  ADD CONSTRAINT PK_IDKHoa PRIMARY KEY (IDKHoa)
ALTER TABLE BENH ADD CONSTRAINT PK_IDBENH  PRIMARY KEY (IDBENH )
ALTER TABLE ChiTietDonThuoc ADD CONSTRAINT PK_IDDonThuoc  PRIMARY KEY (IDDonThuoc)

--Khóa ngoại của các  bảng: 
ALTER TABLE PhieuDangKyKhamBenh ADD CONSTRAINT FK_HoSoBenhAn_PhieuDKiKham FOREIGN KEY (IDHoSo) REFERENCES HoSoBenhAn(IDHoSo)
ALTER TABLE LePhi ADD CONSTRAINT FK_HoSoBenhAn_LePhi FOREIGN KEY (IDHoSo) REFERENCES HoSoBenhAn(IDHoSo)
ALTER TABLE PhieuNhapXuatVien ADD CONSTRAINT FK_HoSoBenhAn_PhieuXuatVien FOREIGN KEY (IDHoSo) REFERENCES HoSoBenhAn(IDHoSo)
ALTER TABLE VienPhi ADD CONSTRAINT FK_HoSoBenhAn_VienPhi FOREIGN KEY (IDHoSo) REFERENCES HoSoBenhAn(IDHoSo)
ALTER TABLE PhieuKhamBenh ADD CONSTRAINT FK_HoSoBenhAn_PhieuKham FOREIGN KEY (IDHoSo) REFERENCES HoSoBenhAn(IDHoSo)
ALTER TABLE PhieuXetNghiem ADD CONSTRAINT FK_HoSoBenhAn_PhieuXetNghiem FOREIGN KEY (IDHoSo) REFERENCES HoSoBenhAn(IDHoSo)
ALTER TABLE BacSi ADD CONSTRAINT FK_KHOA_BacSi FOREIGN KEY (IDKHoa) REFERENCES KHOA(IDKHoa)
ALTER TABLE ChiTietPhieuKhamBenh ADD CONSTRAINT FK_BacSi_ChiTietBenh FOREIGN KEY (IDBacSi) REFERENCES BacSi(IDBacSi)
ALTER TABLE ChiTietPhieuKhamBenh ADD CONSTRAINT FK_PhieuKham_ChiTietBenh FOREIGN KEY (IDPKB) REFERENCES PhieuKhamBenh(IDPKB)
ALTER TABLE  ToaThuoc ADD CONSTRAINT FK_ChiTietBenh_ToaThuoc FOREIGN KEY (IDPKB) REFERENCES ChiTietPhieuKhamBenh(IDPKB)S
ALTER TABLE ChiTietPhieuKhamBenh ADD CONSTRAINT FK_BENH_ChiTietBenh FOREIGN KEY (IDBENH) REFERENCES BENH(IDBENH)
ALTER TABLE ToaThuoc ADD CONSTRAINT FK_ChiTietDonThuoc_ToaThuoc FOREIGN KEY (IDDonThuoc) REFERENCES ChiTietDonThuoc(IDDonThuoc)
ALTER TABLE ChiTietDonThuoc ADD CONSTRAINT FK_Thuoc_ChiTietDonThuoc FOREIGN KEY (IDThuoc) REFERENCES Thuoc(IDThuoc)


